# -*- coding: utf-8 -*-
"""Untitled31.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FRJatgVmUhIo0ZwbkRIuih-smOJkMt2v
"""

from pyspark.sql import SparkSession
from pyspark.ml.evaluation import BinaryClassificationEvaluator

spark = SparkSession.builder \
    .appName("IEEE-Fraud-Evaluation") \
    .getOrCreate()

df = spark.read.parquet("/output/ieee_fraud_predictions")

evaluator = BinaryClassificationEvaluator(
    labelCol="label",
    rawPredictionCol="prediction",
    metricName="areaUnderROC"
)

auc = evaluator.evaluate(df)
print("✅ MODEL AUC SCORE:", auc)

spark.stop()