# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10BoCxK0tX5_p5YkFdMJiLIMtt-YjuLh4
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import col
from pyspark.ml.feature import VectorAssembler

spark = SparkSession.builder \
    .appName("IEEE-Fraud-Feature-Engineering") \
    .getOrCreate()

print("✅ Reading CSV data directly...")

identity = spark.read.option("header", True).option("inferSchema", True).csv("/data/train_identity.csv")
transaction = spark.read.option("header", True).option("inferSchema", True).csv("/data/train_transaction.csv")

print("✅ Joining identity + transaction...")
df = transaction.join(identity, on="TransactionID", how="left")

print("✅ Selecting ML-safe features...")
selected_cols = [
    "TransactionAmt",
    "dist1",
    "C1", "C2", "C3",
    "D1", "D2",
    "V1", "V2", "V3",
    "isFraud"
]

df = df.select(*[c for c in selected_cols if c in df.columns])
df = df.dropna(subset=["isFraud"])
df = df.fillna(0)

feature_cols = [c for c in df.columns if c != "isFraud"]

assembler = VectorAssembler(
    inputCols=feature_cols,
    outputCol="features"
)

df_ml = assembler.transform(df).select(
    col("features"),
    col("isFraud").alias("label")
)

print("✅ Final ML dataset count:", df_ml.count())
df_ml.show(5)

print("✅ Writing ML dataset...")
df_ml.coalesce(1).write.mode("overwrite").parquet("/output/ieee_fraud_features")

print("✅ SUCCESS: Features saved at /output/ieee_fraud_features")

spark.stop()