# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U6qtwi7lhGO854QETniSDS2k_KdILM9D
"""

from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("IEEE-Fraud-Ingestion") \
    .getOrCreate()

# Load CSV files
tx = spark.read.csv("/data/train_transaction.csv", header=True, inferSchema=True)
idn = spark.read.csv("/data/train_identity.csv", header=True, inferSchema=True)

# Join datasets
df = tx.join(idn, on="TransactionID", how="left")

print("Total records:", df.count())
df.show(5)

# Save joined data
df.write.mode("overwrite").parquet("/output/ieee_fraud_joined")

spark.stop()