# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11XfQ0KI5IUTE598XVP5bygL8px_Eim1v
"""

from pyspark.sql import SparkSession
from pyspark.ml.classification import LogisticRegressionModel
from pyspark.ml.feature import VectorAssembler
from pyspark.sql.functions import col

spark = SparkSession.builder \
    .appName("IEEE-Fraud-Prediction") \
    .getOrCreate()

# Load feature data
df = spark.read.parquet("/output/ieee_fraud_features")

# Load trained model
model = LogisticRegressionModel.load("/output/ieee_fraud_model")

# Run predictions
predictions = model.transform(df)

# Show sample results
predictions.select("label", "prediction", "probability").show(10)

# Save predictions
predictions.select(
    col("label"),
    col("prediction"),
    col("probability")
).write.mode("overwrite").parquet("/output/ieee_fraud_predictions")

spark.stop()