# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19--jdgR3sBOzcCTTk8nEw33h664oZKnC
"""

from pyspark.sql import SparkSession
from pyspark.ml.classification import LogisticRegression
from pyspark.ml.evaluation import BinaryClassificationEvaluator
from pyspark.sql.functions import rand

spark = SparkSession.builder \
    .appName("IEEE-Fraud-Model-Training") \
    .getOrCreate()

print("✅ Loading ML features...")
df = spark.read.parquet("/output/ieee_fraud_features")

print("✅ Splitting into train / test...")
train_df, test_df = df.randomSplit([0.8, 0.2], seed=42)

print("✅ Training Logistic Regression model...")
lr = LogisticRegression(
    featuresCol="features",
    labelCol="label"
)

model = lr.fit(train_df)

print("✅ Running predictions...")
predictions = model.transform(test_df)

print("✅ Evaluating model...")
evaluator = BinaryClassificationEvaluator(
    labelCol="label",
    metricName="areaUnderROC"
)

auc = evaluator.evaluate(predictions)
print("🔥 MODEL ROC-AUC SCORE:", auc)

print("✅ Saving trained model...")
model.save("/output/ieee_fraud_model")

print("✅ Training complete. Model saved at /output/ieee_fraud_model")

spark.stop()